### ISSUE TITLE
0.7-P2 MessageBuffer doesn't work on Android 4.3

### ISSUE THREAD

**Issue by axeon** [msgpack/msgpack-java#174]
I used MessageBuffer on Android OS(4.3) . But these error and exceptions occurred.
It's  an urgent issue for now,Please fix it, thanks!

Could not find class 'sun.nio.ch.DirectBuffer', referenced from method org.msgpack.core.buffer.MessageBuffer.<init>
Could not find class 'sun.nio.ch.DirectBuffer', referenced from method org.msgpack.core.buffer.MessageBuffer.releaseBuffer
Could not find class 'sun.nio.ch.DirectBuffer', referenced from method org.msgpack.core.buffer.MessageBuffer.putByteBuffer

java.lang.NoSuchMethodError: sun.misc.Unsafe.putByte
	at org.msgpack.core.buffer.MessageBuffer.putByte(MessageBuffer.java:349)
	at org.msgpack.core.MessagePacker.writeByte(MessagePacker.java:150)
	at org.msgpack.core.MessagePacker.packRawStringHeader(MessagePacker.java:486)
	at org.msgpack.core.MessagePacker.packString(MessagePacker.java:400)

**Comment by xuwei-k** [comment]
duplicate? https://github.com/msgpack/msgpack-java/issues/101

**Comment by axeon** [comment]
maybe duplicated.
but the same issue was post on 25 May 2014, haven't resolved until now.
android is important platform for msgpack, so this issue is very very urgent!

**Comment by xerial** [comment]
OK. 
I'll try to resolve this.

**Comment by axeon** [comment]
@xerial
Thank you! I will cooperate with you to test it on android.

**Comment by xerial** [comment]
Duplicate of #101
